---
name: CI
on: workflow_dispatch

jobs:
  Build-in-Matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Make
        run: make
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: built-libs
          path: '**/*.so.1'
