---
name: CI
on: workflow_dispatch

jobs:
  Build-in-Matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Make x64
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
        run: make libs
      - name: 'Setup Visual C++'
        if: ${{ success() && matrix.os == 'windows-latest' }}
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: MSBuild x64
        if: ${{ success() && matrix.os == 'windows-latest' }}
        run: msbuild.exe "$env:GITHUB_WORKSPACE\Argon2.sln" -t:Argon2OptDll:Build -p:Configuration=ReleaseStatic -p:Platform=x64
      - name: Upload (Ubuntu)
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: built-libs-ubuntu
          path: '**/*.so.1'
      - name: Upload (Windows)
        if: ${{ success() && matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: built-libs-windows
          path: 'vs2015/build/**/*.dll'
