---
name: CI
on: workflow_dispatch

jobs:
  Build-in-Matrix:
    strategy:
      matrix:
        os: [ 'ubuntu-22.04', 'windows-2022', 'macos-14' ]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: 'Clone'
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: 'Make (Ubuntu)'
        if: ${{ success() && startsWith(matrix.os, 'ubuntu') }}
        run: make libs
      - name: 'Make (MacOS)'
        if: ${{ success() && startsWith(matrix.os, 'macos') }}
        run: make libs
      - name: 'Setup Visual C++'
        if: ${{ success() && startsWith(matrix.os, 'windows') }}
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      - name: 'MSBuild x64'
        if: ${{ success() && startsWith(matrix.os, 'windows') }}
        run: msbuild.exe "$env:GITHUB_WORKSPACE\Argon2.sln" -t:Argon2OptDll -p:Configuration=ReleaseStatic -p:Platform=x64
      - name: 'List Output Binaries (Ubuntu)'
        if: ${{ success() && startsWith(matrix.os, 'ubuntu') }}
        run: |-
          shopt -s globstar
          set +e
          echo $PWD
          ls -la -R **/libargon*.so*
      - name: 'List Output Binaries (MacOS)'
        if: ${{ success() && startsWith(matrix.os, 'macos') }}
        shell: pwsh
        run: |-
          Write-Output "Current directory: $PWD"
          Get-ChildItem '**/libargon*.dylib*' -Recurse | Select-Object -ExpandProperty 'FullName'
      - name: 'Upload (Ubuntu)'
        if: ${{ success() && startsWith(matrix.os, 'ubuntu') }}
        uses: actions/upload-artifact@v5
        with:
          name: built-libs-ubuntu
          path: '**/*.so.1'
      - name: 'Upload (Windows)'
        if: ${{ success() && startsWith(matrix.os, 'windows') }}
        uses: actions/upload-artifact@v5
        with:
          name: built-libs-windows
          path: 'vs2015/build/**/*.dll'
      - name: 'Upload (MacOS)'
        if: ${{ success() && startsWith(matrix.os, 'macos') }}
        uses: actions/upload-artifact@v5
        with:
          name: built-libs-macos
          path: '**/*.dylib'
